import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Wallet, FileText } from "lucide-react";
import { PageHeader } from "../../components/common/ui.jsx";
import { DataTableShell, TableSkeleton, EmptyState } from "../../components/feedback.jsx";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "../../components/ui/table.jsx";
import { usePageTitle } from "../../hooks.js";
import { payrollService } from "../../api/index.js";
import { queryKeys } from "../../constants.js";
import { PayslipViewModal } from "./PayslipView.jsx";

const MONTH_NAMES = [
  "", "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

function formatMoney(amount) {
  if (amount == null) return "—";
  return new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
}

export function MyPayslipsPage() {
  usePageTitle("My Payslips");
  const [viewPayslip, setViewPayslip] = useState(null);

  const { data: payslips, isLoading, isError } = useQuery({
    queryKey: queryKeys.payroll.mine,
    queryFn: () => payrollService.listMine(),
  });

  return (
    <>
      <PageHeader
        title="My Payslips"
        description="View your past payslips and salary details."
      />

      <DataTableShell
        title="Payslip History"
        description="All your generated payslips, newest first."
      >
        {isLoading ? (
          <TableSkeleton rows={5} />
        ) : isError ? (
          <EmptyState icon={FileText} title="Failed to load payslips" description="Please try again later." />
        ) : !Array.isArray(payslips) || payslips.length === 0 ? (
          <EmptyState
            icon={Wallet}
            title="No payslips yet"
            description="Your payslips will appear here once payroll has been generated by your administrator."
          />
        ) : (
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Period</TableHead>
                  <TableHead className="text-right">Gross Salary</TableHead>
                  <TableHead className="text-right">Deductions</TableHead>
                  <TableHead className="text-right">Net Pay</TableHead>
                  <TableHead className="text-right">Generated</TableHead>
                  <TableHead className="w-[80px]">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {payslips.map((p) => (
                  <TableRow key={p.id}>
                    <TableCell>
                      <span className="font-medium text-sm">{MONTH_NAMES[p.payPeriodMonth]} {p.payPeriodYear}</span>
                    </TableCell>
                    <TableCell className="text-right text-sm">{formatMoney(p.grossSalary)}</TableCell>
                    <TableCell className="text-right text-sm text-red-600 dark:text-red-400">
                      −{formatMoney(p.totalDeductions)}
                    </TableCell>
                    <TableCell className="text-right text-sm font-semibold">{formatMoney(p.netPay)}</TableCell>
                    <TableCell className="text-right text-xs text-muted-foreground">
                      {new Date(p.generatedAt).toLocaleDateString()}
                    </TableCell>
                    <TableCell>
                      <button
                        className="inline-flex items-center gap-1 text-sm text-primary hover:underline font-medium transition-colors duration-150"
                        onClick={() => setViewPayslip(p)}
                      >
                        View
                      </button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </DataTableShell>

      {viewPayslip && (
        <PayslipViewModal payslip={viewPayslip} onClose={() => setViewPayslip(null)} />
      )}
    </>
  );
}
