services:
  - type: web
    name: hr-saas-backend
    runtime: image
    image:
      url:
    dockerfilePath: ./hr-saas/Dockerfile
    dockerContext: ./hr-saas
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: DB_USERNAME
        value: postgres.nkpgyzeoejfxuqdpneuv
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_API_URL
        value: https://api.brevo.com/v3/smtp/email
      - key: MAIL_FROM_ADDRESS
        value: no-reply@hrsaas.com
      - key: FRONTEND_BASE_URL
        value: https://coral-sooty.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://coral-sooty.vercel.app
      - key: SERVER_PORT
        value: 8080
      - key: JAVA_VERSION
        value: "20"
    healthCheckPath: /actuator/health
    autoDeploy: true
