package com.hrsaas.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Sends transactional emails via the Brevo (formerly Sendinblue) SMTP API.
 *
 * Every public method is annotated with {@code @Async} so the caller doesn't
 * block while the email is sent. If the Brevo API key is missing, emails are
 * silently skipped with a log warning — this keeps the app functional during
 * local development without a real mail provider.
 *
 * Email HTML is generated by {@link EmailTemplate}, which produces
 * self-contained inline-CSS templates compatible with Gmail, Outlook, and
 * Apple Mail.
 */
@Service
public class MailService {

    private static final Logger log = LoggerFactory.getLogger(MailService.class);

    private final RestTemplate restTemplate;

    /** Brevo sender address — configured via {@code MAIL_FROM_ADDRESS} env var. */
    @Value("${app.mail.from}")
    private String fromAddress;

    /** Frontend base URL — used to build clickable links in emails. */
    @Value("${app.frontend.base-url}")
    private String frontendBaseUrl;

    /** Brevo API key — configured via {@code BREVO_API_KEY} env var. */
    @Value("${brevo.api.key}")
    private String brevoApiKey;

    public MailService(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    // ──────────────────────────────────────────────
    //  Public email methods (all @Async)
    // ──────────────────────────────────────────────

    /**
     * Welcome email sent to the admin immediately after company registration.
     * Contains the company slug (login identifier) and a link to the login page.
     */
    @Async
    public void sendCompanyWelcomeEmail(String toEmail, String companyName, String companySlug) {
        String subject = "Welcome to CoralHR, " + companyName;
        String html = EmailTemplate.companyWelcome(companyName, companySlug, frontendBaseUrl + "/login");
        send(toEmail, subject, html);
    }

    /**
     * Invitation email sent when an admin creates a new employee.
     * The employee clicks the link to set their password and activate their account.
     * The link expires after the configured number of hours (default 72h).
     */
    @Async
    public void sendEmployeeInvitation(String toEmail, String firstName, String companyName, String inviteLink) {
        String subject = "You've been invited to join " + companyName + " on CoralHR";
        String html = EmailTemplate.employeeInvitation(firstName, companyName, inviteLink);
        send(toEmail, subject, html);
    }

    /**
     * Notification email sent when an admin approves or rejects a leave request.
     * Includes the leave type and a clear visual status indicator.
     */
    @Async
    public void sendLeaveStatusEmail(String toEmail, String firstName, String status, String leaveType) {
        String subject = "Your " + leaveType.toLowerCase() + " leave request has been " + status.toLowerCase();
        String html = EmailTemplate.leaveStatus(firstName, status, leaveType);
        send(toEmail, subject, html);
    }

    /**
     * Password reset email containing a time-limited link (1 hour).
     * If the user didn't request this, they can safely ignore the email.
     */
    @Async
    public void sendPasswordResetEmail(String toEmail, String firstName, String resetLink) {
        String subject = "Reset your CoralHR password";
        String html = EmailTemplate.passwordReset(firstName, resetLink);
        send(toEmail, subject, html);
    }

    // ──────────────────────────────────────────────
    //  Internal send helper
    // ──────────────────────────────────────────────

    /**
     * Builds and sends a single email via the Brevo SMTP API.
     * Silently returns if the API key is not configured (dev mode safety).
     *
     * @param toEmail  recipient email address
     * @param subject  email subject line
     * @param htmlBody full HTML body (produced by {@link EmailTemplate})
     */
    private void send(String toEmail, String subject, String htmlBody) {
        try {
            // ── Guard: missing API key ──
            if (brevoApiKey == null || brevoApiKey.isBlank()) {
                log.warn("Brevo API key not configured — skipping email to {}. Set BREVO_API_KEY to enable.", toEmail);
                return;
            }

            // ── Validate required fields ──
            if (toEmail == null || toEmail.isBlank()) {
                log.error("send() called with empty recipient — subject: {}", subject);
                return;
            }
            if (fromAddress == null || fromAddress.isBlank()) {
                log.error("MAIL_FROM_ADDRESS not configured — cannot send email to {}", toEmail);
                return;
            }

            String url = "https://api.brevo.com/v3/smtp/email";

            // ── Build Brevo API request ──
            HttpHeaders headers = new HttpHeaders();
            headers.set("api-key", brevoApiKey);
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.setAccept(List.of(MediaType.APPLICATION_JSON));

            Map<String, Object> emailData = new HashMap<>();

            // Sender
            emailData.put("sender", Map.of(
                    "name", "CoralHR",
                    "email", fromAddress
            ));

            // Recipient
            String trimmedEmail = toEmail.trim();
            List<Map<String, String>> toList = new ArrayList<>();
            toList.add(Map.of("email", trimmedEmail, "name", trimmedEmail));
            emailData.put("to", toList);

            // Content
            emailData.put("subject", subject);
            emailData.put("htmlContent", htmlBody);

            log.debug("Sending email via Brevo: to={}, subject={}", trimmedEmail, subject);

            // ── Send ──
            HttpEntity<Map<String, Object>> request = new HttpEntity<>(emailData, headers);
            ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.POST, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("Email sent to {} — subject: {}", trimmedEmail, subject);
            } else {
                log.error("Brevo API returned HTTP {} for email to {} — subject: {}",
                        response.getStatusCode(), trimmedEmail, subject);
            }
        } catch (Exception e) {
            log.error("Failed to send email to {} — subject: {} — error: {}", toEmail, subject, e.getMessage(), e);
        }
    }
}
